/*
 * Copyright (c) 2026 Mert Senturk
 * SPDX-License-Identifier: Apache-2.0
 *
 * TinyQuant: analog project, generated by the TinyQuant Python flow (gen/).
 * The layout (gds/, lef/) is the design; this file describes the connectivity of the
 * top-level blocks for documentation and for the Tiny Tapeout checks.
 */

`default_nettype none

module tt_um_senturk_mert_tinyquant (
    input  wire       VGND,
    input  wire       VDPWR,    // 3.3v core power supply
    input  wire [7:0] ui_in,    // Dedicated inputs
    output wire [7:0] uo_out,   // Dedicated outputs
    input  wire [7:0] uio_in,   // IOs: Input path
    output wire [7:0] uio_out,  // IOs: Output path
    output wire [7:0] uio_oe,   // IOs: Enable path (active high: 0=input, 1=output)
    inout  wire [7:0] ua,       // Analog pins, only ua[5:0] can be used
    input  wire       ena,      // always 1 when the design is powered, so you can ignore it
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);
    wire [9:0] sar_d;
    wire sar_conv, sar_clk, sar_rstn, nsen;
    wire dsm_y, dsm_ph1, dsm_clk, dsm_rstn, dsm_en, dsm_t0, dsm_t1;
    wire vcm_s, vcm_d;

    // 10-bit asynchronous Vcm-based SAR with switchable passive noise shaping
    tq_sar10ns sar (.VDD(VDPWR), .VSS(VGND), .vinp(ua[0]), .vinn(ua[1]), .clk(sar_clk), .rstn(sar_rstn),
                    .vcm(vcm_s), .nsen(nsen), .d(sar_d), .conv(sar_conv));

    // 2nd-order switched-capacitor delta-sigma modulator
    tq_dsm2 dsm (.VDD(VDPWR), .VSS(VGND), .vinp(ua[0]), .vinn(ua[1]), .clk(dsm_clk), .rstn(dsm_rstn),
                 .en(dsm_en), .t0(dsm_t0), .t1(dsm_t1), .vcm(vcm_d), .y(dsm_y), .phmon(dsm_ph1));

    // VDD/2 references (poly-resistor dividers with MOS decoupling)
    tq_vcm vcms (.VDD(VDPWR), .VSS(VGND), .vcm(vcm_s));
    tq_vcm vcmd (.VDD(VDPWR), .VSS(VGND), .vcm(vcm_d));

    // mode control and output multiplexing (custom 3.3 V logic cells)
    tq_ctl ctl (.VDD(VDPWR), .VSS(VGND), .clk(clk), .rst_n(rst_n), .mode(ui_in[0]), .nsen_in(ui_in[1]),
                .t0_in(ui_in[2]), .t1_in(ui_in[3]), .sar_d(sar_d), .conv(sar_conv), .y(dsm_y), .phmon(dsm_ph1),
                .sar_clk(sar_clk), .sar_rstn(sar_rstn), .nsen(nsen), .dsm_clk(dsm_clk), .dsm_rstn(dsm_rstn),
                .dsm_en(dsm_en), .dsm_t0(dsm_t0), .dsm_t1(dsm_t1), .uo(uo_out), .uio(uio_out[2:0]));

    assign uio_out[7:3] = {5{VGND}};
    assign uio_oe[2:0] = {3{VDPWR}};
    assign uio_oe[7:3] = {5{VGND}};

endmodule
